import { ArrowRight, BookmarkPlus, Clapperboard, Play, Sparkles, Star } from 'lucide-react'
import { Link } from 'react-router-dom'
import { PosterCard } from '../components/PosterCard'
import { useMovies } from '../context/MovieContext'
import { featured } from '../data/featured'
export function Home() {
  const { movies, saved, toggleSaved, loading } = useMovies()
  const picks = movies.slice(0, 4)
  const isSaved = (movie: { id: number; title: string }) => saved.some((item) => item.id === movie.id || item.title.trim().toLocaleLowerCase('pt-BR') === movie.title.trim().toLocaleLowerCase('pt-BR'))
  return <div className="page-content"><section className="hero"><img className="hero-image" src="https://image.tmdb.org/t/p/original/8bcoRX3hQRHufLPSDREdvr3YMXx.jpg" alt=""/><div className="hero-shade"/><div className="hero-copy"><span className="eyebrow"><Sparkles size={14}/> ESCOLHA DA SEMANA</span><div className="hero-title-row"><span className="hero-number">01</span><h1>O Grande Hotel<br/><em>Budapeste</em></h1></div><p>Uma aventura cheia de charme, mistério e personagens inesquecíveis. Sua próxima sessão merece essa escolha.</p><div className="hero-meta"><span><Star size={14} fill="currentColor"/> 8.1</span><span>2014</span><span>Comédia · Aventura</span><span className="age-badge">12</span></div><div className="hero-actions"><Link className="primary-button" to={`/filme/${featured.id}`} state={{ movie: featured }}><Play size={16} fill="currentColor"/> Explorar filme</Link><button className={`secondary-button ${isSaved(featured) ? 'is-saved' : ''}`} onClick={() => toggleSaved(featured)}><BookmarkPlus size={16}/>{isSaved(featured) ? 'Na minha lista' : 'Quero assistir'}</button></div></div><span className="hero-caption"><Clapperboard size={13}/> CINEMA PARA SENTIR</span><div className="hero-dots"><i/><i/><i/></div></section><section className="section-block"><div className="section-heading"><div><span className="eyebrow">SELEÇÃO PARA SUA PRÓXIMA SESSÃO</span><h2>Descobertas da vez<span className="green-dot">.</span></h2></div><Link className="text-link" to="/catalogo">Ver catálogo completo <ArrowRight size={15}/></Link></div>{loading ? <div className="loading-line">Preparando sua sessão<span>...</span></div> : <div className="movie-grid">{picks.map((movie) => <PosterCard key={movie.id} movie={movie} saved={isSaved(movie)} onToggle={toggleSaved}/>)}</div>}</section></div>
}
